### ISSUE TITLE
documentation lacking some basic info

### ISSUE THREAD

**Issue by faxm0dem** [RavuAlHemio/grafana-weathermap-panel#1]
Hi,

just wanted to know how to install it, and what datasources were supported. I'm interested in adding Elasticsearch support

cheers

**Comment by RavuAlHemio** [comment]
Hi,

I've added some more content to the README. Is it of any help?

Cheers!

**Comment by faxm0dem** [comment]
awesome, thanks!

**Comment by faxm0dem** [comment]
Do you have an example config?
What data is needed? I guess some coordinates and a value to plot the colors?

**Comment by RavuAlHemio** [comment]
Sorry, no example config; I cannot possibly know what other people's Grafana setup looks like. However, I've written a tutorial as `docs/minimal.md` that describes the steps to the most minimal of weathermaps (two nodes and one connecting edge) to get people started.

**Comment by faxm0dem** [comment]
thanks so much!
